version: "3.9"

services:
  postgres:
    image: postgres:13.3-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.4-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

# Apps
  scheduler:
    image: evebot/scheduler:dev
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP: scheduler
    env_file: .env.compose
    ports:
      - '3000:3000'

  status:
    image: evebot/status-sync:dev
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        APP: status-sync
    env_file: .env.compose

volumes:
  postgres-data:
  redis-data:
