# Documentation about Garden projects can be found at https://docs.garden.io/using-garden/projects
# Reference for Garden projects can be found at https://docs.garden.io/reference/project-config

# The Garden apiVersion for this project.
#
# The value garden.io/v0 is the default for backwards compatibility with
# Garden Acorn (0.12) when not explicitly specified.
#
# Configuring garden.io/v1 explicitly in your project configuration allows
# you to start using the new Action configs introduced in Garden Bonsai (0.13).
#
# Note that the value garden.io/v1 will break compatibility of your project
# with Garden Acorn (0.12).
apiVersion: garden.io/v1

# Indicate what kind of config this is.
kind: Project

# The name of the project.
name: evebot-backend

defaultEnvironment: dev

# A list of environments to configure for the project.
environments:
  - name: dev
    defaultNamespace: evebot-dev
  - name: prod
    defaultNamespace: evebot
    production: true


# A list of providers that should be used for this project, and their configuration. Please refer to individual
# plugins/providers for details on how to configure them.
providers:
  - name: kubernetes
    environments:
      - dev
      - prod
    context: homelab
    buildMode: local-docker
    deploymentRegistry:
      hostname: registry.homelab.monster
      namespace: evebot
    namespace: ${environment.namespace}

---

kind: RenderTemplate
name: scheduler
template: service-template
inputs:
  environment: ${environment.name}
  sentrySecretName: SCHEDULER_SENTRY_DSN
  forwardPort: 8888

---

kind: RenderTemplate
name: status-sync
template: service-template
inputs:
  environment: ${environment.name}
  sentrySecretName: STATUS_SYNC_SENTRY_DSN

---

kind: RenderTemplate
name: universe-sync
template: service-template
inputs:
  environment: ${environment.name}
  sentrySecretName: SCHEDULER_SENTRY_DSN

---

