apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-sync
spec:
  selector:
    matchLabels:
      app: status-sync
  template:
    metadata:
      labels:
        app: status-sync
    spec:
      containers:
      - name: status-sync
        image: registry.homelab.monster/evebot/status-sync
        resources:
          requests:
            memory: "128Mi"
            cpu: "25m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: REDIS_HOST
            value: "redis-redis-ha-haproxy"
          - name: REDIS_PORT
            value: "6379"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: evebot-secrets
                key: POSTGRES_DSN
