apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
      - name: scheduler
        image: registry.homelab.monster/evebot/scheduler
        resources:
          requests:
            memory: "128Mi"
            cpu: "25m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
        env:
          - name: REDIS_HOST
            value: "redis-redis-ha-haproxy"
          - name: REDIS_PORT
            value: "6379"
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: evebot-secrets
                key: POSTGRES_DSN
